/*
  # Populate Data Requirements for DLI 2 DLRs

  1. Purpose
    - Populate the data_requirements field for DLI 2 DLRs
    - Based on the data requirements document screenshots for DLI 2-a and DLI 2-b
  
  2. DLRs Updated
    - DLR 2.0.1: Notification of Sikkim Industrial and Services Sector Development & Investment Policy 2023
    - DLR 2.2.1: Information on Innovation Hub creation
    - DLR 2.2.2: Details of 2 Incubation or Acceleration services
    - DLR 2.4.1: Details of 4 incubation or acceleration services (cumulative)
    - DLR 2.4.2: Commercial loans data for women-led/youth-led enterprises
    - DLR 2.5.2: Commercial loans data for women-led/youth-led enterprises (cumulative)
*/

-- DLR 2.0.1
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'Notification of the Sikkim Industrial and Services Sector Development & Investment Policy 2023.'
)
WHERE code = 'DLR 2.0.1';

-- DLR 2.2.1
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'Information on the creation of an Innovation Hub'
)
WHERE code = 'DLR 2.2.1';

-- DLR 2.2.2
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'Details of Establishment of Two Incubation or Acceleration services',
  'Details of Incubation Services',
  'Beneficiary Details of Incubation Services',
  'The Approval Letters for the establishment of 2 Acceleration Services in the Non-Farm Sector.',
  'Activity Reports/Evaluation Studies on the establishment of 2 Acceleration Services in the Non-Farm Sector',
  'Information on the Acceleration Services in the Non-Farm Sector from the Program MIS/Official documents'
)
WHERE code = 'DLR 2.2.2';

-- DLR 2.4.1
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'The Approval Letters for the establishment of 2 additional Incubation Services in the Non-Farm Sector',
  'Activity Reports/Evaluation Studies on the establishment of 2 additional Incubation Services in the Non-Farm Sector',
  'Information on the Incubation Services in the Non-Farm Sector from the Program MIS/Official documents',
  'Approval Letters for the establishment of two additional acceleration Services in the Non-Farm Sector',
  'Activity Reports/Evaluation Studies on the establishment of two additional Acceleration Services in the Non-Farm Sector.',
  'Details of Acceleration Services documents in the Non-Farm Sector from the Program MIS/ official documents.'
)
WHERE code = 'DLR 2.4.1';

-- DLR 2.4.2
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'The Activity Reports/Evaluation Studies on the Commercial loans provided to beneficiary enterprises supported in the non-farm sector',
  'Data generated by Program MIS/Official documents on the Commercial loans provided to beneficiary enterprises in the non-farm sector'
)
WHERE code = 'DLR 2.4.2';

-- DLR 2.5.2
UPDATE dlis
SET data_requirements = jsonb_build_array(
  'The Activity Reports/Evaluation Studies on the Commercial loans provided to beneficiary enterprises supported in the non-farm sector',
  'Data generated by Program MIS/Official documents on the Commercial loans provided to beneficiary enterprises in the non-farm sector'
)
WHERE code = 'DLR 2.5.2';